### ISSUE TITLE
Deploy Horizontal Intake

### ISSUE THREAD

**Issue by dec1701** [RIT-VEX-U/2020-2021-LITTLE#8]
The horizontal intake motors will run to deploy the intake.
There will be a limit switch underneath that will be pressed when the limit switch is deployed.
The intake will continue trying to deploy until it is successful (but maybe there should be a timeout in case it gets stuck or fails to activate the limit switch for any reason)
![VEXDeployPseudocode.jpg](https://app.gitkraken.com/api/glo/boards/5ed00103c2baa000110fbf1e/attachments/5f9472900d832b00112000ee)

[v5code-project-DeployTest.zip](https://app.gitkraken.com/api/glo/boards/5ed00103c2baa000110fbf1e/attachments/5f9da9fa0d832b0011230f0b)

**Comment by ChrisORiv** [comment]
Tried spinning motor on right arm to deploy right arm using DeployTest code in this task. Arm would not deploy at maximum velocity. Need to rethink deployment method.
